### ISSUE TITLE
Results on rotated images

### ISSUE THREAD

**Issue by trungpham2606** [magicleap/SuperPointPretrainedNetwork#7]
@ddetone my results after trying to retrain your model based on your released code:
![image](https://user-images.githubusercontent.com/35657426/68639090-1102f200-0536-11ea-8ba3-06a1aa64e561.png)

It is able now to cope with rotation angles greater than 45 degree. 
![image](https://user-images.githubusercontent.com/35657426/68639172-54f5f700-0536-11ea-85db-65ae5232c484.png)

The threshold I was setting is 0.3
I modified your training a bit and trained the descriptor part only. ( 1000 coco images + 1000 hpatches images, 21 epochs)

**Comment by ddetone** [comment]
Great! I tried some experiments like this and noticed that I got more false positive matches then I like compared to the vanilla SuperPoint. Thanks for sharing. Since this isn't really an issue, I'm going to close this.
